#!/usr/bin/env python 
import os, sys, inspect

cmd_subfolder = os.path.realpath(os.path.abspath(os.path.join(os.path.split(inspect.getfile( inspect.currentframe() ))[0],"python")))
if cmd_subfolder not in sys.path:
  sys.path.insert(0, cmd_subfolder)

from OMPython import OMShell

shell = OMShell(os.path.curdir)

# vim:ts=2:sw=2:expandtab:
