#!/bin/bash

if [[ $# != 1 ]]
then
    echo usage: $0 script
    exit
fi

curDir=$PWD
export OPENMODELICALIBRARY=$PWD:$OPENMODELICALIBRARY
tmpDir=/tmp/$(whoami)
mkdir -p $tmpDir
cd $tmpDir
pids=`pgrep "omc|OMShell|OMPlot"`
if [[ "$pids" != "" ]]
then
    echo killing: $pids
    kill $pids
fi
omc +s $curDir/$1
