#!/bin/bash
export OPENMODELICALIBRARY=$PWD:$PWD/aircraft:$OPENMODELICALIBRARY
tmpDir=/tmp/$(whoami)
mkdir -p $tmpDir
cd $tmpDir
pids=`pgrep "omc|OMShell|OMPlot"`
if [[ "$pids" != "" ]]
then
    echo killing: $pids
    kill $pids
fi
OMShell-terminal
