#!/usr/bin/env python
import os
import sys
import inspect
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib.ticker import EngFormatter
import numpy as np
from OMPython import OMShell
from DyMat import DyMatFile

# find root path of project
root_path = os.path.abspath(os.path.join(
  inspect.getfile(inspect.currentframe()),
  os.path.pardir))
curdir = os.path.abspath(os.path.curdir)

if len(sys.argv) == 2:
  shell = OMShell(root_path)
  print shell.run_script(sys.argv[1])
else:
  print "usage", sys.argv[0], "script", 
  sys.exit(1)

matFile = DyMatFile(shell.get_build_path()+"/Datcom_res.mat")
x = matFile.data('body.airframe.r_0[1]');
y = matFile.data('body.airframe.r_0[3]');

ax = plt.subplot(111)
formatter = EngFormatter(unit='m', places=1)
ax.xaxis.set_major_formatter(formatter)
ax.yaxis.set_major_formatter(formatter)
ax.plot(x, y)
plt.show()

# vim:ts=2:sw=2:expandtab:
