#!/usr/bin/env python
# generate time till failure plot
import os
import sys
import inspect
import OMPython

root_path = os.path.abspath(os.path.join(
  inspect.getfile(inspect.currentframe()),
  os.path.pardir,os.path.pardir))

shell = OMPython.OMShell(root_path,echo=True);
returns = shell.executeMultiLine("cd();help();");

for item  in returns:
  print item

# vim:ts=2:sw=2:expandtab:
